name: CI Tests workflow

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Decrypt the puzzle inputs
        run: dotnet run --project AoC.CLI --decrypt
        env:
          AocPuzzleInputCryptoKey: ${{ secrets.AOC_PUZZLE_INPUT_CRYPTO_KEY }}
      - name: Run tests and collect coverage
        run: dotnet test AoC.Tests --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      - name: Publish unit test code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-code-coverage-results
          path: AoC.Tests/TestResults/*/coverage.cobertura.xml
