name: App releases

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Publish and release
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100
    - name: Workload restore
      run: dotnet workload restore
    - name: Publish Android app
      run: dotnet publish AoC.MAUI -f:net7.0-android -c:Release
    - name: Publish Windows CLI
      run: dotnet publish AoC.CLI -c Release -r win-x64 --self-contained -p:PublishSingleFile=true
    - uses: "marvinpinto/action-automatic-releases@latest"
      name: Create GitHub release
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Release"
        files: |
          AoC.MAUI/bin/Release/net7.0-android/publish/com.rws.aoc2022-Signed.apk
          AoC.CLI/bin/Release/net7.0/win-x64/publish/AoC.CLI.exe
